name: Deploy Dags

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          sparse-checkout:
            batch
    
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.AIRFLOW_CORE_IP }} >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.AIRFLOW_WORKER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy DAGs to Core
        run: |
          rsync -avz \
            --rsync-path="sudo rsync" \
            batch/dags/raw/ \
            batch/dags/silver/ \
            batch/dags/gold/ \
            batch/plugins/ \
            ${{ secrets.AIRFLOW_USER }}@${{ secrets.AIRFLOW_CORE_IP }}:/home/${{ secrets.AIRFLOW_USER }}/airflow/dags/ &&

          rsync -avz \
            --rsync-path="sudo rsync" \
            requirements.txt \
            Dockerfile \
            ${{ secrets.AIRFLOW_USER }}@${{ secrets.AIRFLOW_CORE_IP }}:/home/${{ secrets.AIRFLOW_USER }}/airflow/ &&

          ssh ${{ secrets.AIRFLOW_USER }}@${{ secrets.AIRFLOW_CORE_IP }} \
            "cd /home/${{ secrets.AIRFLOW_USER }}/airflow && \
            echo 'AIRFLOW__LOGGING__REMOTE_LOGGING=True' > .env && \
            echo 'AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER=s3://team6-batch' >> .env && \
            echo 'AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID=aws_conn_id' >> .env && \
            docker compose down && \
            docker compose up -d --build"

      - name: Deploy DAGs to Worker
        run: |
          rsync -avz \
            --rsync-path="sudo rsync" \
            batch/dags/raw/ \
            batch/dags/silver/ \
            batch/dags/gold/ \
            batch/plugins/ \
            ${{ secrets.AIRFLOW_USER }}@${{ secrets.AIRFLOW_WORKER_IP }}:/home/${{ secrets.AIRFLOW_USER }}/airflow/dags/ &&

          rsync -avz \
            --rsync-path="sudo rsync" \
            batch/dbt \
            ${{ secrets.AIRFLOW_USER }}@${{ secrets.AIRFLOW_WORKER_IP }}:/home/${{ secrets.AIRFLOW_USER }}/ &&

          rsync -avz \
            --rsync-path="sudo rsync" \
            requirements.txt \
            ${{ secrets.AIRFLOW_USER }}@${{ secrets.AIRFLOW_WORKER_IP }}:/home/${{ secrets.AIRFLOW_USER }}/airflow/ &&

          rsync -avz \
            --rsync-path="sudo rsync" \
            Dockerfile_Worker \
            ${{ secrets.AIRFLOW_USER }}@${{ secrets.AIRFLOW_WORKER_IP }}:/home/${{ secrets.AIRFLOW_USER }}/airflow/Dockerfile &&

          ssh ${{ secrets.AIRFLOW_USER }}@${{ secrets.AIRFLOW_CORE_IP }} \
            "cd /home/${{ secrets.AIRFLOW_USER }}/airflow && \
            echo 'AIRFLOW__LOGGING__REMOTE_LOGGING=True' > .env && \
            echo 'AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER=s3://team6-batch' >> .env && \
            echo 'AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID=aws_conn_id' >> .env && \
            echo 'SNOWFLAKE_ACCOUNT=${{ secrets.SNOWFLAKE_ACCOUNT }}' >> .env && \
            echo 'SNOWFLAKE_USER=${{ secrets.SNOWFLAKE_USER }}' >> .env && \
            echo 'SNOWFLAKE_PASSWORD=${{ secrets.SNOWFLAKE_PASSWORD }}' >> .env && \
            echo 'SNOWFLAKE_ROLE=${{ secrets.SNOWFLAKE_ROLE }}' >> .env && \
            echo 'SNOWFLAKE_WAREHOUSE=${{ secrets.SNOWFLAKE_WAREHOUSE }}' >> .env && \
            echo 'SNOWFLAKE_DATABASE=${{ secrets.SNOWFLAKE_DATABASE }}' >> .env && \
            echo 'SNOWFLAKE_SCHEMA=SILVER' >> .env && \
            docker compose down && \
            docker compose up -d --build && \
            docker exec -it airflow-airflow-worker-1 bash -c 'source /opt/dbt_venv/bin/activate && cd /opt/dbt && dbt debug --profiles-dir /opt/dbt'"
            
      - name: Slack Notification (Always)
        if: always() # 성공/실패 여부와 상관없이 실행
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
                  {
                    "text": "${{ job.status == 'success' && '✅' || '❌' }} *AWS CD Result*: Github Actions ${{ job.status }}\n
                    *Author:* ${{ github.actor }}\n
                    *Repo:* <${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>\n
                    *Branch:* <${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}|${{ github.ref_name }}>\n
                    *Commit:* <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>\n"
                  }
